language: objective-c
osx_image: xcode7
before_install:
- gem install fir-cli --no-ri --no-rdoc
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/XC_Ad_Hoc_comlivinggame.mobileprovision.enc -d -a -out scripts/profile/XC_Ad_Hoc_comlivinggame.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
script:
- xctool -project TestDemo.xcodeproj -scheme TestDemo -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="TestDemo"
  - DEVELOPER_NAME="iPhone Distribution: moyou technology co., LTD (W5P65H2M57)"
  - PROFILE_NAME="XC_Ad_Hoc_comlivinggame"
  - secure: tOtzy/UHb36C6/etZPKtVA2tRJuSWjNUjCkNlnwYJN+nOw8JnUoRravdqhQB1lDos5VB2N++6A1/+ciigKb9noc2So6lt+15PJIJ4wuZpmGuPMMcpmymosk8t3hqK/UDB8Xltc3YMB59x5F60fJeYKAK5RQYv2mLzWdNkoZeQIA/TEZvu+rmfuLCvR59a//XsUA/oRAWz8SKspcxqjPJWQOusuSj5LJ07lbQkSWN9Fgdr9MGJIiOedTNqmCWkWzsE4M0dcg2POVTfWE9XKNdOGhUtFAOkxDqSqwMLGj4oeaY0N9cLOznSlzSn+AtVlPZ2hgLMQZyanZXMBGUAz5xKN5BgwHjTxTzlzcgzuJtXlw3U33S3eF3DGrdTENDJ6EdFa+tDqhcSUIjI7dz9DnSc4YURH3rubZ9uWSkxmdh695EhI3k6SrBCOK/7ULKgJFrKyAIhHJIvTP08n0j531Es+EXR1p99aB/mTzb+iZOEWKcC/7bQrBRxrnH1DzeAMbDKYvaUFg5AFJ4YxpP8JcRPj+WyrZMyOkxnafmEwAxWNlryBlDOW7p4XRiueXqMWp+j+E6Zs5zxnHBO8HxQj0NPOaFtgNWmd2vyWxUJZZMW+LAQ/Tx8CqOqUlnU/84jIZQlECoRLT0jPTu5FV3egvKgryw+jpLyt7+N3mkc4qTJ+c=
  - secure: pEl3agQhlN6MDqkbejZXXjOcfQZKl6asTVlqUcgTSqLCqlAfUxGe3eLAsoeoKfsGQLG5h5NPyIIFzQLDpBwN8Wpfb/II7vX0gmgfae2PcRCTQgkS2+YSOWC7aBkSxbu05BMncoQIKwfjOuenX8ec6dR4kp91fAVZUDGz5WnyOl5+gTaYfHTLKZIQN5f6lD4GwpOp0ungy0MvJQadrSB91ZeaVC6e1y7NjaaY5IKonOYBz0X36rfvzZw1e1AmoQxLsp2W00KxzDiDFigrec01RBnn7t/pI7H8NytEvNQFBxc57IDreTq+XEv+DYmQ897IP8Emd46TeB04bLNqupeCwktJtIYLf4CXPusKwFtQXccBaZlK/1t+TY6PXtl9RA3tCJHk/GHaFOCKfMNYdX2qOe5Qr26Ebte0BZVoFi8ySQT3AVDGrIxaEaiRRbvVJGcqn0I7krcVTGZe9y9tG7Dm1PyvSOGzrEVmtIjBYzISBzLZMpNlh8L8gMnbQcQXwLQ2kRN2vuTeaSl7qMLZwboYUrAAXsOJD/hBdC6oVT45++2kgAl9OYfPZwnI0HGb0HuBLB6bBJGEMnsC1VzzTZRupuegS2t2xYNWf4DQqSfIUN4UfqkywHw0V3s67XpttXetoo/vC5cztpl/OxG4xsL+BZbSR0rSZGXjcqFc/m6kGmY=
