language: objective-c
osx_image: xcode7
before_install:
- gem install fir-cli --no-ri --no-rdoc
- brew update
- brew install xctool
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TestDemo.mobileprovision.enc -d -a -out scripts/profile/TestDemo.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
script:
- xctool -workspace TestDemo.xcodeproj -scheme TestDemo test

after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="TestDemo"
  - 'DEVELOPER_NAME="iPhone Distribution: bo zhong"'
  - PROFILE_NAME="TestDemo"
  - secure: MgpOWsVPLkf4eLpgie7FtNDprjj2s9TyRHl9CXz1MxgRr1QUGVXXjCvM1186sQqkq/GLMddY1YZxQN1gwZvHHOwiJHjDu0Hq8CwYhSl149uIMzKTD4vWpxRfiDv7+KMbiRLX0LpUQhJ0quWv3y7bm2lDN0ZqmLHQuik/igsnLGZz4d64V6OlPE+kDosmyIgt/OCMB/8Q+fb5JLD91C0zFMM0Q8O0VA1sjnDtJae3wrQX0+HegSm2sP7BMe6co/l8WXbAnKkQdx3YO/ZNL+TINvfmF4LK2bavJa+AGj5Vn15RiZbLckgTdffGVlWxNAMy2XMQ9qnS4aOTLOYZdmKxC9+v0fQ9uDq3kvCq9bNdNcPtCCmPWqhrEiUF8ev4fhZlJluqpY3K8/WvIXMOKjeXILMK2BQ6VESHWAcBNE2E3hP9Ztn8+SZ+uRDNzUUUpUwlOjfgbK1fwtwSMOHSL5LkiqEMlGDbpO5eXjzUSLPlnLoc6MGTYeGiY2N2HeJ3jFEs9potRLwW/1aisAApdgObgasYGRUwde7QzeNWUi7EFQOYObroVy5jrAMgcmv78FZnsHjc4ktDDyRwYiDBhMZu26D9VOglkdk7zosdAzZblZUoby0Xih6wt3sHz37PZAFIa0DQ1emf/TnZP1lqVq8So6Hz0gtlSA7jQAF4FPp+qsU=
  - secure: eoVspKpzBD4DbM68OgsO1lAOLkmCn+M620/snZB5mQz/3IcTMNDS1rWVHY80CikLwwsWCqxFD7K9BWIF6XRGPDhQ8DLjtg/p0StNb9gJB5zfNF9SgXb0YyBeB/KqgHVHqhsprKLJYWDPFEXnbfQnhO2glXhzrTVi0XHm3QoBsyl7zOTDY7zhQ4BMJ5jJ1ju9NJ6d3y6Zmk+HkljAo44d5bCN7PB6OkPwumz6BrWfxrGlr3pVqUbpd2XtZp/IsGleNnpQR+W1E7z18A+Fh4JNakQwjbFT8S5eORcVYL2dwwWvkCm8etoxY/lFtI7hmXcJUOjNl4nBOmlZz/f1hVmNfmrQs5A+Qafkc5uNfJwPHaGOcGIe/SHqi/YqkJktVk19xSemPAk4U724eOwE+nmO2AJiyvqoAu3JtHdRMaq96xxEF7/Zwuv4RdW0bCxa9lj6UY8LT6Psv4LAon+2PEkwrWS/WRN7CNifrpDOdhFiXfpqfxDr6Ze/F0LU52y8miv2agev8bgnrjbrCyU1YdU8mNgQmIjRKLYnw/xA2nZ6erTjSEHxz79nxFXMax253DxU86wu+PuGIV4j10soWT/0rqtuPLQdNsVTcY9ZPJox5y806IPqaDGKd1eGNPLBHu+vqrh1hSB5T3pid+5/+9G4zdCvMgLeDevzWs852feOJmo=
