language: objective-c
osx_image: xcode7
before_install:
- gem install fir-cli --no-ri --no-rdoc
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TestDemo.mobileprovision.enc -d -a -out scripts/profile/TestDemo.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
script:
- xcodebuild -project TestDemo.xcodeproj -target TestDemo -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
env:
  global:
  - APP_NAME="TestDemo"
  - 'DEVELOPER_NAME="iPhone Developer: bo zhong"'
  - PROFILE_NAME="TestDemo"
  - secure: Yr6oCvAsFgJkZdZOjfenydReebfYYspdrRVNUrLzdldNvEVQfg/ryAc3w2iiCBt0OgtCgs9CLsvNl+1tDeag2oyFZgOnNGep2Jfhw/pyxhyV0I9ZOIsWPlja1qAKF4pTOXr9fVcEjUSKc6H/Iu41q37e390Qc1qAdtsoVVKfffdP0bMwyBgFCRWE49GZApv4ijjX3rXU2hxJFuqAQGvdJ3c/pFSqhk2wRZ9faLN0I2Z2SaPKQIjn+ezh2JWaqsp3pTBjDOQpPUTCy/j5i8sujU+ZW+D04xkNrsoDARJuCrWZrUvI/9TILftkjbPqDCZQ07T3Dzf3+yL0HeqXzFxhmsvZlH3jIOt6hE98jK6nkgNwxsdEcyKy4Iz4710Kecq+BeycP+/c58h/WAzuXFFCOQC4h9VvTY6pNb1Ictq9itHNweJKCNOuRMovkdREKuKcTGFWgz7vTqdKxHJePfCHU9/waOwG/Wt1BmFEiOzarG39pyu1gDx19VTmkB1Cy6y1DK6F27vgBP3bJOTIHJ5w3YhVBys5k2P7s1JjeX24Ontl/kPs/0NuwfHALjxJ0Ah2en8j0Q76cXy9px9ZrDwP4wpa1fVT+eG2UKCfJFp4amCoWK+LbnszbOurMsSdKd0AnulphNT3rjj/3MiKlsT/DhcxppL/TUnDUDXZXTnThXQ=
  - secure: lGAlfb/8rT0wJJblXdNn+kI26vbKdFyNSb0K/5S4k4iL0QPp5MA4kUNca8nFBhD2HDVjCiDsEWKy+/h480CPU+04ALa6kRqo9EcMFHgsL7Hjj4R0O36kF9dZS+GenPrm20fFClhhRDfCxjY/W6vGbwA8m5ZysX7ma9IKVmdzslXZxmrm0g3+CF0eTNW1AcNCG2cv6sZQYWG7jAdeFEnGa5pbt2/reyEK0xmCa2Pil+CsWcsOMN8Y1S17/HtNRZwEERpl+Qpx4hBieF9c57FHXV/nysyqu+EEP7qUfW0nx8MwejgCY8cwljIFcIJSYYxAQcrfwwx+A5O3ZtheFSWGvOqjidomVPQyRt0qoABCMblF8vq8ZCImu095Bq+o7U3GZdrABrULJJxbP4DOjWUZkJvMlkoQlCjovSD+CWo8qpKb4OmMQe+q0gHDAtdFOWHUy/ZF/ARlmNK4k5eHDexye9Gt1ETbuuAzcrC8FkeLlSgU6viG9fksNROPPHWlejYUrflAAo1InRQ+dkJe5HjR6p6xIbjE9IjhNdMatXIrSYyC6oYSpYEyhXUBmRgfrECe6SpSQPA+9XLTKDPgwN3qyp5GwtZUfL/A7M4opPkPIbtZDqiInHMmB6WJhu+zm6FxZqaXBEB100h5/X66XB7sg2hRolPgSGWSuv7i5/95DZo=
